### ISSUE TITLE
Python 3.7 has the below error.

### ISSUE THREAD

**Issue by karunakarhv** [corentone/python-ping#1]
.. C:\Users\kvenkatesh\eclipse-workspace\python3_ping.py:216: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  default_timer = time.clock()
Traceback (most recent call last):
  File "C:\Users\kvenkatesh\eclipse-workspace\python3_ping.py", line 603, in <module>
    verbose_ping("heise.de")
  File "C:\Users\kvenkatesh\eclipse-workspace\python3_ping.py", line 589, in verbose_ping
    delay  =  do_one(dest_addr, timeout)
TypeError: do_one() missing 4 required positional arguments: 'hostname', 'timeout', 'mySeqNumber', and 'packet_size'

**Comment by kuzmeech** [comment]
On 3.7 I was able to fix it with this diff: 
```
79c79
<     default_timer = time.clock
---
>     default_timer = time.perf_counter
```
